const seasoningList = 
[
    {product: "Salt "},
    {product: "Pepper"},
    {product: "Sugar"},
    {product: "Basil"},
    {product: "Bay Leaves"},
    {product: "Cayenne"},
    {product: "Chili Powder"},
    {product: "Cinnamon--Ground and Stick"},
    {product: "Cloves"},
    {product: "Cumin"},
    {product: "Curry Powder"},
    {product: "Dill Weed"},
    {product: "Garlic Powder"},
    {product: "Ginger--Ground"},
    {product: "Nutmeg--Ground"},
    {product: "Onion Powder"},
    {product: "Oregano"},
    {product: "Paprika"},
    {product: "Red Pepper Flakes"},
    {product: "Rosemary"},
    {product: "Saffron"},
    {product: "Sage"},
    {product: "Tarragon"},
    {product: "Thyme"},
    {product: "Vanilla"},
]
export default seasoningList