const vegetableList = [
    {product: "Avocado"},
    {product: "Beans"},
    {product: "Broccoli"},
    {product: "Cabbage"},
    {product: "Carrot"},
    {product: "Cauliflower"},
    {product: "Celery"},
    {product: "Coriander"},
    {product: "Corn"},
    {product: "Cucumber"},
    {product: "Eggplant"},
    {product: "Garlic"},
    {product: "Ginger"},
    {product: "Lettuce"},
    {product: "Mushroom"},
    {product: "Olive"},
    {product: "Onion"},
    {product: "Oregano"},
    {product: "Pickle"},
    {product: "Potato"},
    {product: "Pumpkin"},
    {product: "Seeds"},
    {product: "Shallot"},
    {product: "Spinach"},
    {product: "Sweet Potato"},
    {product: "Thyme"},
    {product: "Tomato"},
    {product: "Zucchini"}
  ]
  export default vegetableList